### ISSUE TITLE
Review use of rounding the number floors to nearest integer value

### ISSUE THREAD

**Issue by dmey** [TEB-model/teb#32]
In `bem_morpho.F90` the number of floors is calculated correctly but then rounded to the closest integer before being converted again to real -- see code below:

https://github.com/TEB-model/teb/blob/1185a20cba37eb003ac4dd7414f79ee390e9d55f/src/teb/bem_morpho.F90#L90

@VakankGrang @ValeryMasson is there any reason for doing this instead of keeping at as real? This is useful when average building values are used.

**Comment by VakankGrang** [comment]
Dear David, 

You should keep an integer number of floors since otherwise the calculations 
are not consistent with the morphological assumptions of BEM. There is 
one ground floor, a roof, and depending on the number of floors a certain 
number of intermediate floors. This must be an integer. 
It might be promising to render the model a bit more precise by considering 
an attic, which would correspond to 0.XX floors, but in this case the physical 
equations would have to be adapted. It cannot be done by just setting 
the number of floors to a real number. 

Cheers, 

Robert 



De: "dmey" <notifications@github.com> 
À: "TEB-model/teb" <teb@noreply.github.com> 
Cc: "VakankGrang" <robert.schoetter@meteo.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Vendredi 31 Juillet 2020 14:34:35 
Objet: [TEB-model/teb] Review use of rounding the number floors to nearest integer value (#32) 





In bem_morpho.F90 the number of floors is calculated correctly but then rounded to the closest integer before being converted again to real -- see code below: 

[ https://github.com/TEB-model/teb/blob/1185a20cba37eb003ac4dd7414f79ee390e9d55f/src/teb/bem_morpho.F90#L90 | https://github.com/TEB-model/teb/blob/1185a20cba37eb003ac4dd7414f79ee390e9d55f/src/teb/bem_morpho.F90#L90 ] 


[ https://github.com/VakankGrang | @VakankGrang ] [ https://github.com/ValeryMasson | @ValeryMasson ] is there any reason for doing this instead of keeping at as real? This is useful when average building values are used.

**Comment by dmey** [comment]
Closing as moved to email discussion for now.
